---
- name: Restart network
  hosts: all
  become: true

  tasks:
    - name: restrat network
      systemd:
        name: network
        state: restarted

- name: inetRouter
  hosts: inetRouter
  become: true

  tasks:
    - name: inetRouter script
      command: /vagrant/scripts/inetRouter.sh

      
- name: centralRouter
  hosts: centralRouter
  become: true

  tasks:
    - name: centralRouter script
      command: /vagrant/scripts/centralRouter.sh


- name: office1Router
  hosts: office1Router
  become: true

  tasks:
    - name: office1Router script
      command: /vagrant/scripts/office1Router.sh


- name: office2Router
  hosts: office2Router
  become: true

  tasks:
    - name: office2Router script
      command: /vagrant/scripts/office2Router.sh


- name: centralServer
  hosts: centralServer
  become: true

  tasks:
    - name: centralServer script
      command: /vagrant/scripts/centralServer.sh


- name: office1Server
  hosts: office1Server
  become: true

  tasks:
    - name: office1Server script
      command: /vagrant/scripts/office1Server.sh


- name: office2Server
  hosts: office2Server
  become: true

  tasks:
    - name: office2Server script
      command: /vagrant/scripts/office2Server.sh
      